### ISSUE TITLE
How to Listen to the events?

### ISSUE THREAD

**Issue by ghost** [Riari/laravel-forum-frontend#16]
How is it possible to listen your forum frontend events in mij App?

$events->listen('UserViewingThread', function ($foo, $bar) {}); in my EventServiceProvider -> Boot doesn't work.

Thanks. Great Package!

**Comment by Riari** [comment]
I'm not sure why that wouldn't work. They're just standard Laravel events. The package even listens to that exact same event, although it uses a class instead of a callback: https://github.com/Riari/laravel-forum-frontend/blob/1.0/src/ForumFrontendServiceProvider.php#L106

Try doing it like that instead.

**Comment by Riari** [comment]
Ah, I think I see the problem; events have no aliases, they're just identified by their class names. Try doing `listen('Riari\Forum\Frontend\Events\UserViewingThread' ...)` (or import the class and use `UserViewingThread::class`).

**Comment by ghost** [comment]
Thanks! It works!
