### ISSUE TITLE
Discussion - make it easier to style

### ISSUE THREAD

**Issue by garygreen** [Riari/laravel-forum-frontend#20]
As I understand laravel-forum is more geared towards the concept of creating your own views to style the forum OR you use laravel-forum-frontend as a basic starting point.

There are a few ways you could style the forum:
1. Copy and paste all the views, hack away as you like - the problem with this is if new features get added e.g. to the forms or anything get's fixed, you'll be stuck on an outdated theme and will need to update manually.
2. Override only certain views in your app - this is a better option, but still creates a problem of what if new features are added, new columns, etc, you'll still need to update manually.
3. **Proposed solution** - remain agnostic in the way the theme is displayed, but make it easier to style all pages by adding classes in a well-defined format e.g. `threads-table` `post-comment` `post-username`

Step 3 is the same approach [`atom`](https://atom.io/) uses to create a 'hackable text editor' -- in essence you can pretty much style it in any way you like because it provides useful css classes.

Of course there will likely be a case of needing to employ #2 at some point if you want very specific theme, or even javasacript may help, but I think #3 will move towards helping create a very customised looking forum in itself.

**Comment by Riari** [comment]
Overriding styles on forum elements is already possible since IDs are set on the containers - `category`, `thread` and even `post` when viewing a post standalone. Using those with some clever selectors, it's possible to target almost anything.

It's not semantically ideal though, and I like the idea of sprinkling the views with a few additional classes here and there. Given that the IDs exist, the classes can be more generic - `thread` for a thread row in a post, `post` for a post row in a thread, `user-info`, etc. I'll look at adding those.

Thanks for the suggestions!

**Comment by Riari** [comment]
[Done](https://github.com/Riari/laravel-forum-frontend/releases/tag/1.1.6).
