### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by hellosunnyhihi** [Riari/laravel-forum-frontend#30]
Hi
I'm using Laravel 7, I have to install riari/laravel-forum ~5.0 (dev)
But I can not install and using laravel-forum-frontend version after.

How do I have to do to fix this problem?
Thanks

**Comment by Riari** [comment]
Hi,

Version 5.0 of laravel-forum isn't finished yet and doesn't make use of this package because it provides the front-end out of the box.

You can try using 5.0-dev without this package as it's 90% feature complete, but I wouldn't recommend it yet as you'll likely encounter issues until the first stable release.

In the meantime, if you need Laravel 7 support, see https://github.com/Team-Tea-Time/laravel-forum/issues/213 - someone kindly forked version 4 and made it compatible with Laravel 6+, so you could try that.

Thanks

**Comment by Calytic** [comment]
Looks like a fairly simple change, I'd prefer not to fork this: https://github.com/jetwes/laravel-forum/commit/a6f4b796df9a86887f6e77e1cecccbeaa1c01a3a

**Comment by Riari** [comment]
That's fair. If there are no compatibility issues out of the box, I'll do a new release to include 7 and 8. I'll update this issue and the one I linked when it's ready. 👍🏻

**Comment by hellosunnyhihi** [comment]
thank you so much

**Comment by Riari** [comment]
It's done - laravel-forum 4.2.0 should work for Laravel 6 - 8. The current release of the frontend package should work with it. Let me know if you encounter any issues :)
